### ISSUE TITLE
Extract the structure

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/find-test-names#5]
Instead of the list of describe and test names with tags, need to return the object with the structure of tests

```js
describe('suite', () => {
  it('works')
})

it('loads')
```

Currently we get a list
```
suites: ['suite']
tests: ['works', 'loads']
```

Need to return
```json
{
  "suites": [{
     "suite": {
        "tests": ["works"]
      }
  }],
  "tests": ["loads"]
}
```

**Comment by Narretz** [comment]
Hi @bahmutov I would like to take a shot at this. 

I assume the structure should also have the tags for suites and tests? And should the tags be inherited? I.e. child suites and tests inherit them from their parent suites?

**Comment by bahmutov** [comment]
I am thinking for each spec file we should get a list of suites and tests

```
[
  { title: "works" }, // test
  "suite1": [ ... ] // tests and suites inside suite1
]
```
