### ISSUE TITLE
Using a TypeScript type on a test causes spec parsing to fail 

### ISSUE THREAD

**Issue by droca** [bahmutov/find-test-names#6]
Having the following test code, using TypeScript to define const with a type:

```
import { UserType } from '../../support/data/users';

describe('test description', () => {
  it('test it', {tags:'@tag2'} () => {
    const user : UserType = { email: 'email', password:'password' }; 
  });
});
```

And the following configuration, as seen on the debug code of the cypress-grep tool
```
cypress-grep Cypress config env object: { grepTags: '@tag2', grepFilterSpecs: true }
```

I get the following error, coming from the `acorn` library, since it finds a character that it's not expecting coming from the TypeScript assigning a type to the const

![image](https://user-images.githubusercontent.com/5064227/143944141-56cf3a80-86c4-443b-aea2-54d352c470dc.png)

This makes it impossible for me to properly use the `cypress-grep` tool with my TS tests. Since the issue is basically in this library, because the use of acorn, I think that reporting it here is more fitting.

I wonder if there's a solution for this.
Cheers

**Comment by Narretz** [comment]
Just hit this, too. This is because the lib uses https://www.npmjs.com/package/acorn, a JS parser only. I actually wrote a lib / function for extracting test names that uses babel + recast. I think something similar is necessary here.

**Comment by bahmutov** [comment]
I welcome a pull request to add ts parser

**Comment by Narretz** [comment]
Cool! Here's a quick and dirty one: https://github.com/bahmutov/find-test-names/pull/7
